version: '2.2'
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/home/app
    ports:
    - "3000:3000"
    links:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./local_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    command: redis-server
    volumes:
      - '.:/home/app'
  #sidekiq:
  #  depends_on:
  #    - 'redis'
  #  build: .
  #  command: bundle exec sidekiq
  #  volumes:
  #    - .:/home/app

volumes:
  ecommerce_db:
