version: '2.2'
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    stdin_open: true
    tty: true
    volumes:
      - .:/home/app
    ports:
    - "3000:3000"
    links:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./local_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    command: redis-server
    volumes:
      - '.:/home/app'
    ports:
    - "6379:6379"
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    volumes:
      - .:/home/app
      - ./tmp/sidekiq:/home/app/tmp/sidekiq
    env_file:
      - .env

volumes:
  ecommerce_db:
